### ISSUE TITLE
Feature: add "snip code" function to contextmenu.

### ISSUE THREAD

**Issue by MairwunNx** [amaembo/screenshoter#17]
I think it would not be bad to have the "Snip Code" button in the context menu of the editor. This may not simplify much the code snip if one of the hands is busy, for example, I have a pizza with one hand and it is not convenient for me to press a few keys, it is easier for me to take a screenshot with the mouse in this case.

**Comment by amaembo** [comment]
This action is already added into the main Edit menu:
![image](https://user-images.githubusercontent.com/5114450/58064493-8a83de00-7bac-11e9-8198-fd0a35ba4917.png)

If you want to add it to context menu, you can do this via Settings:

![image](https://user-images.githubusercontent.com/5114450/58064551-c1f28a80-7bac-11e9-9f5d-785a2d405ee1.png)

And it will appear for you:

![image](https://user-images.githubusercontent.com/5114450/58064570-d2a30080-7bac-11e9-9288-cb691ada2525.png)

I hesitate to add it for everybody by default, because this context menu is already huge.

**Comment by MairwunNx** [comment]
@amaembo thanks, resolved!
